C:\Users\ncshr\AppData\Local\Programs\Python\Python36\python.exe C:/Users/ncshr/PycharmProjects/fss18/w12/w1.py

-----| testTuples |-----------------------
# pass

-----| testDict |-----------------------
# pass

-----| testSet |-----------------------
# pass

-----| testCount |-----------------------
# pass

-----| testFunctions |-----------------------
# pass

-----| testControlFlow |-----------------------
# pass

-----| testTruthiness |-----------------------
# pass

-----| testRandom |-----------------------
# pass

-----| testGenerator |-----------------------
# pass

-----| testIte |-----------------------
# pass

-----| testRegex |-----------------------
# pass

-----| testListCompr |-----------------------
# pass

-----| testSorting |-----------------------
# pass

-----| testModules |-----------------------
# pass

-----| testStrings |-----------------------
# pass

-----| testLists |-----------------------
# pass

-----| testException |-----------------------
# pass

-----| testArithmetic |-----------------------
# pass

-----| testWhitespace |-----------------------
# pass

-----| testingFailure |-----------------------
# this one must fail.. just to
# test if the  unit test system is working
Traceback (most recent call last):
  File "C:/Users/ncshr/PycharmProjects/fss18/w12/w1.py", line 19, in k
    f()
  File "C:/Users/ncshr/PycharmProjects/fss18/w12/w1.py", line 187, in testingFailure
    assert 1==2
AssertionError


-----| testingSuccess |-----------------------
# if this one fails, we have a problem!
# pass

# pass= 20 fail= 1 %pass = 95%

Process finished with exit code 0
